const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const prefs={nodeIntegration:true,contextIsolation:false};
const original=details=>details.url==='about:blank'?{action:'allow',overrideBrowserWindowOptions:{webPreferences:prefs,show:false}}:{action:'deny'};
const wc={_windowOpenHandler:original,isDestroyed:()=>false,setWindowOpenHandler(fn){this._windowOpenHandler=fn;}};
const api={};
vm.runInNewContext(fs.readFileSync(__dirname+'/popup-main.cjs','utf8'),{exports:api,require:()=>({webContents:{fromId:()=>wc}}),setTimeout,clearTimeout,Map});
api.arm(1);
assert.equal(wc._windowOpenHandler({url:'https://example.com',features:''}).action,'deny');
assert.notEqual(wc._windowOpenHandler,original);
const result=wc._windowOpenHandler({url:'about:blank',features:'popup,width=700'});
assert.equal(result.overrideBrowserWindowOptions.type,'panel');
assert.equal(result.overrideBrowserWindowOptions.webPreferences,prefs);
assert.equal(result.overrideBrowserWindowOptions.show,false);
assert.equal(wc._windowOpenHandler,original);
api.arm(1);api.disarm(1);assert.equal(wc._windowOpenHandler,original);
api.arm(1);const newer=()=>({action:'deny'});wc.setWindowOpenHandler(newer);api.disarm(1);assert.equal(wc._windowOpenHandler,newer);
console.log('Passed: only intended popup modified; Obsidian preferences preserved; original handler restored; newer handler preserved.');
