const assert=require('node:assert/strict');
const {withoutPanel}=require('./session-layout.cjs');
const leaf=(id,file='notes/example.md')=>({id,type:'leaf',state:{type:'markdown',state:{file}}});
const win=(id,children,currentTab=0)=>({id,type:'window',children:[{id:id+'-tabs',type:'tabs',children,currentTab}],x:10,y:20,width:760,height:743});
const original={main:{type:'split',children:[leaf('main')]},active:'panel',floating:{type:'floating',children:[win('panel-window',[leaf('panel')]),win('ordinary',[leaf('normal-same-note')])]}};
const before=JSON.stringify(original);
const saved=withoutPanel(original,new Set(['panel']));
assert.equal(saved.floating.children.length,1);
assert.equal(saved.floating.children[0].id,'ordinary');
assert.equal(saved.active,'main');
assert.equal(JSON.stringify(original),before);
assert.equal(saved.main,original.main);
assert.deepEqual(withoutPanel(JSON.parse(JSON.stringify(saved)),new Set(['panel'])),saved);
const only={...original,floating:{type:'floating',children:[win('panel-window',[leaf('panel')])]}};
assert.equal(withoutPanel(only,new Set(['panel'])).floating,undefined);
const mixed={...original,active:'normal',floating:{type:'floating',children:[win('shared',[leaf('panel'),leaf('normal')],1)]}};
const kept=withoutPanel(mixed,new Set(['panel']));
assert.equal(kept.floating.children[0].children[0].currentTab,0);
assert.equal(kept.active,'normal');
assert.equal(kept.floating.children[0].children[0].children[0].id,'normal');
assert.equal(withoutPanel(original,new Set(['unknown'])),original);
assert.equal(withoutPanel(original,new Set()),original);
console.log('PASS: panel excluded from saved/restored layout; ordinary windows including the same note, selected tabs, and main workspace preserved.');
